// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_multisig
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-01-31, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/substrate
// benchmark
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_multisig
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./frame/multisig/src/weights.rs
// --template=.maintain/frame-weight-template.hbs
// --header=HEADER-APACHE2
// --raw

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_multisig.
pub trait WeightInfo {
	fn create(z: u32) -> Weight;
	fn create_and_execute(z: u32) -> Weight;
	fn vote() -> Weight;
	fn vote_and_execute(z: u32) -> Weight;
	fn unvote() -> Weight;
	fn unvote_and_execute(z: u32) -> Weight;
	fn unvote_and_cancel() -> Weight;
	fn retain_asset() -> Weight;
}

/// Weights for pallet_multisig using the Substrate node and recommended hardware.
pub struct Weights<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for Weights<T> {
	// Storage: Assets Asset (r:1 w:0)
	// Storage: Assets Account (r:1 w:0)
	// Storage: DeipStakeVoting Votings (r:1 w:1)
	// Storage: DeipStakeVoting Votes (r:2 w:1)
	// Storage: DeipStakeVoting States (r:1 w:1)
	// Storage: DeipStakeVoting Calls (r:0 w:1)
	fn create(z: u32, ) -> Weight {
		(196_450_000 as Weight)
			.saturating_add((2_000 as Weight).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: Assets Asset (r:1 w:0)
	// Storage: Assets Account (r:1 w:0)
	// Storage: DeipStakeVoting Votings (r:1 w:1)
	// Storage: DeipStakeVoting Votes (r:2 w:1)
	// Storage: DeipStakeVoting States (r:1 w:1)
	// Storage: DeipStakeVoting Calls (r:0 w:1)
	fn create_and_execute(z: u32, ) -> Weight {
		(154_254_000 as Weight)
			// Standard Error: 0
			.saturating_add((4_000 as Weight).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: DeipStakeVoting Votings (r:1 w:0)
	// Storage: DeipStakeVoting Votes (r:2 w:1)
	// Storage: Assets Account (r:1 w:0)
	// Storage: Assets Asset (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: DeipStakeVoting States (r:1 w:1)
	fn vote() -> Weight {
		(87_276_000 as Weight)
			// Standard Error: 0
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: DeipStakeVoting Votings (r:1 w:1)
	// Storage: DeipStakeVoting Votes (r:2 w:1)
	// Storage: Assets Account (r:1 w:0)
	// Storage: Assets Asset (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: DeipStakeVoting States (r:1 w:1)
	// Storage: DeipStakeVoting Calls (r:1 w:1)
	fn vote_and_execute(z: u32, ) -> Weight {
		(141_230_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(8 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: DeipStakeVoting Votings (r:1 w:0)
	// Storage: DeipStakeVoting States (r:1 w:1)
	// Storage: Assets Account (r:1 w:0)
	// Storage: DeipStakeVoting Votes (r:2 w:1)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Assets Asset (r:1 w:0)
	fn unvote() -> Weight {
		(78_065_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: DeipStakeVoting Votings (r:1 w:1)
	// Storage: DeipStakeVoting States (r:1 w:1)
	// Storage: Assets Account (r:1 w:0)
	// Storage: DeipStakeVoting Votes (r:1 w:1)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Assets Asset (r:1 w:0)
	// Storage: DeipStakeVoting Calls (r:1 w:1)
	fn unvote_and_execute(z: u32) -> Weight {
		(104_508_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(z as Weight))
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: DeipStakeVoting Votings (r:1 w:1)
	// Storage: DeipStakeVoting States (r:1 w:1)
	// Storage: Assets Account (r:1 w:0)
	// Storage: DeipStakeVoting Votes (r:2 w:1)
	// Storage: DeipStakeVoting Calls (r:1 w:1)
	fn unvote_and_cancel() -> Weight {
		(105_987_000 as Weight)
			// Standard Error: 0
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: DeipStakeVoting Votes (r:2 w:1)
	// Storage: DeipStakeVoting Votings (r:1 w:0)
	fn retain_asset() -> Weight {
		(39_224_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
