//! Autogenerated weights for pallet_deip_dao
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2022-01-19, STEPS: `[50, ]`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// appchain-deip
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_deip_dao
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// weights.rs


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
    fn create(m: u32) -> Weight;
    fn alter_authority_add_member() -> Weight;
    fn alter_authority_add_member_preserve_threshold() -> Weight;
    fn alter_authority_remove_member() -> Weight;
    fn alter_authority_remove_member_preserve_threshold() -> Weight;
    fn alter_authority_replace_authority(m: u32) -> Weight;
    fn update_dao() -> Weight;
    fn on_behalf() -> Weight;
}

/// Weight functions for pallet_deip_proposal.
pub struct Weights<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for Weights<T> {
    fn create(m: u32) -> Weight {
        (82_598_000 as Weight)
            // Standard Error: 4_000
            .saturating_add((479_000 as Weight).saturating_mul(m as Weight))
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    fn alter_authority_add_member() -> Weight {
        (135_686_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    fn alter_authority_add_member_preserve_threshold() -> Weight {
        (135_061_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    fn alter_authority_remove_member() -> Weight {
        (130_946_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    fn alter_authority_remove_member_preserve_threshold() -> Weight {
        (131_643_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    fn alter_authority_replace_authority(m: u32) -> Weight {
        (96_851_000 as Weight)
            // Standard Error: 7_000
            .saturating_add((715_000 as Weight).saturating_mul(m as Weight))
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    fn update_dao() -> Weight {
        (89_137_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    fn on_behalf() -> Weight {
        (23_231_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
    }
}
